import type { Metadata } from "next";
import "../styles/globals.css";
import { roboto } from "@/utils/fonts";
import GeneralLayout from "@/components/04-templates/GeneralLayout";
import  Header  from "@/components/02-molecules/Header";
import Footer from "@/components/02-molecules/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="flex flex-col">
        <Header />
        <GeneralLayout>
          {children}
        </GeneralLayout>
        <Footer />
      </body>
    </html>
  );
}
